import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerSlot,
}: Readonly<{
  children: React.ReactNode;
  headerSlot: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="py-4 px-12 flex items-center bg-foreground text-background sticky top-0 left-0 right-0 h-16">
          {headerSlot}
        </header>
        <main className="py-8 px-12">{children}</main>
        <footer className="py-8 px-12 flex items-center bg-foreground/20">
          Footer - Bottom of the page
        </footer>
      </body>
    </html>
  );
}
